# Python codes for recomendation system to determine ratings - Based on user id

In [1]:
# Import Python libraries
import pandas as pd
import numpy as np

In [2]:
# Load Dataset
Col_names = ['User_id', 'Movie_id', 'Ratings', 'Unique_timestamp']
Ratings = pd.read_csv('ml-100k/u.data', sep = '\t', names = Col_names, encoding = 'latin_1')
Ratings

       User_id  Movie_id  Ratings  Unique_timestamp
0          196       242        3         881250949
1          186       302        3         891717742
2           22       377        1         878887116
3          244        51        2         880606923
4          166       346        1         886397596
...        ...       ...      ...               ...
99995      880       476        3         880175444
99996      716       204        5         879795543
99997      276      1090        1         874795795
99998       13       225        2         882399156
99999       12       203        3         879959583

[100000 rows x 4 columns]

In [3]:
# Indentifying the number of users in the data set
N_Users = Ratings.User_id.unique().shape[0]
print(f"There are {N_Users} in the dataset")

There are 943 in the dataset

In [4]:
# Create pivot table for the users in the data set based on the ratings
Pivot_table = Ratings.pivot_table (index = 'User_id', columns = 'Movie_id', values = 'Ratings')
Pivot_table

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Replace Nan in the pivot table with 0
Data_matrix = Pivot_table.replace(np.nan, 0)
Data_matrix

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Find cosine similarity for users
from sklearn.metrics.pairwise import pairwise_distances
User_similarity = pairwise_distances(Data_matrix, metric = 'cosine')
User_similarity

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [7]:
# Score calculation
def prediction (Ratings, Similarity, type = 'user'):
    User_ratings_mean = Ratings.mean(axis = 1).to_numpy()
    Ratings_diff = Ratings - User_ratings_mean [:, np.newaxis]
    Predict = User_ratings_mean [:, np.newaxis] + Similarity.dot(Ratings_diff) / np.array([np.abs(Similarity).sum(axis=1)]).T        
    return Predict

In [8]:
# Create prediction table
User_prediction = prediction(Data_matrix, User_similarity, type = 'user')
User_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

# Creating a function to find similarity among users

In [9]:
Iu = int(input("Enter the user number."))
Input_user = Iu

Enter the user number. 34

In [10]:
def UserBased (Input_user, User_similarity, User_prediction, Similar_user_count, thres):
    
    # Convert user sim table to the dataframe
    User_Sim_Table = pd.DataFrame(User_similarity)

    # Finding similarity for user 34 using cosine table
    Sim_Input_User = User_Sim_Table[Input_user].sort_values(ascending = True).head(Similar_user_count).index

    # Convert the similarity values into a list
    Sim_Input_User = list(Sim_Input_User)

    # Select movie id from ratings table for the Similarity_Input_User
    Sim_User_MovieID_List = []
    for Sim_User in Sim_Input_User:
        Sim = list(Ratings[Ratings['User_id']==Sim_User]['Movie_id'])
        Sim_User_MovieID_List.append(Sim)

    # Convert all the lists as a single list
    import itertools
    Sim_User_MovieID_Single_List = list(itertools.chain.from_iterable(Sim_User_MovieID_List))

    # Find unique movie IDs from the list
    Unique_MovieID_Similar_User = set(Sim_User_MovieID_Single_List)

    # Compare the nput movie list with users watched 
    Input_User_Watched_MovieID = list(Ratings[Ratings['User_id']==Input_user]['Movie_id'].values)

    # Create a list to show movie ids to users
    Recom = []
    for per_id in Unique_MovieID_Similar_User:
        if (per_id in Input_User_Watched_MovieID):
            pass
    else:
        Recom.append(per_id)

    # Selection of the highest rate movies that would be selected by the user, based on user prediction
    Highest_rated = []
    User_pred = pd.DataFrame(User_prediction)
    User_pred_Trans = User_pred.T
    Input_User_Pre = pd.DataFrame(User_pred_Trans[Input_user])
    Input_User_Pred = Input_User_Pre.T
    for Re in Recom:
        Value = Input_User_Pred[Re].values
        if(Value >= thres):
            Highest_rated.append(Re)

    # Securing names
    I_Cols = ['Movie id', 'Movie title', 'Release Date', 'Video Release Date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horro', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    Items = pd.read_csv('ml-100k/u.item', sep = '|', names = I_Cols, encoding = 'latin_1')

    # Creating movie list based on recommended movie list
    Movie_title = []
    for MovieID in Highest_rated:
        Movie = Items[Items['Movie id'] == MovieID]['Movie title'].values
        Movie_title.append(Movie)

    # Converting into a pure list
    Movie_Title_List = []
    for M in Movie_title:
        print(M)
        MV = list(M)
        Movie_Title_List.append(MV)

    # Converting into a whole list
    import itertools
    Final_Recommended_Movie = list(itertools.chain.from_iterable(Movie_Title_List))
    print ("The common Movie ID in Recom & User:", list(set(Recom) & set(Input_User_Watched_MovieID)))
    return Final_Recommended_Movie

In [12]:
Recomended_movie = UserBased (5, User_similarity, User_prediction, 2, 0.8)

The common Movie ID in Recom & User: []

In [13]:
len(Recomended_movie)

0