# Python codes for recomendation system to determine ratings based on movie id (item data)

In [1]:
# Import Python libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load Dataset

In [4]:
Col_names = ['User_id', 'Movie_id', 'Ratings', 'Unique_timestamp']
Ratings = pd.read_csv('ml-100k/u.data', sep = '\t', names = Col_names, encoding = 'latin-1')
Ratings

       User_id  Movie_id  Ratings  Unique_timestamp
0          196       242        3         881250949
1          186       302        3         891717742
2           22       377        1         878887116
3          244        51        2         880606923
4          166       346        1         886397596
...        ...       ...      ...               ...
99995      880       476        3         880175444
99996      716       204        5         879795543
99997      276      1090        1         874795795
99998       13       225        2         882399156
99999       12       203        3         879959583

[100000 rows x 4 columns]

In [5]:
N_Items = Ratings.Movie_id.unique().shape[0]
print(f"There are {N_Items} in the dataset")

There are 1682 in the dataset

In [6]:
# Create pivot table based on user id, movie id and rating

In [7]:
Pivot_table = Ratings.pivot_table (index = 'User_id', columns = 'Movie_id', values = 'Ratings')
Pivot_table

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Replace Nan with 0

In [9]:
Data_matrix = Pivot_table.replace(np.nan, 0)
Data_matrix

Movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
User_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# Find cosine similarity for users

In [11]:
from sklearn.metrics.pairwise import pairwise_distances
Item_similarity = pairwise_distances(Data_matrix, metric = 'cosine')
Item_similarity

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [12]:
# Score calculation

In [13]:
def prediction(Ratings, Similarity, type = 'item'):
    Item_ratings_mean = Ratings.mean(axis = 1).to_numpy()
    Ratings_diff = Ratings - Item_ratings_mean [:, np.newaxis]
    Predict = Item_ratings_mean [:, np.newaxis] + Ratings_diff.dot(Similarity) / np.abs(Ratings_diff).sum(axis=1)[:, np.newaxis]
    return Predict

In [14]:
# Prediction table

In [15]:
Item_prediction = prediction(Data_matrix, Item_similarity, type = 'item')
Item_prediction

ValueError: Dot product shape mismatch, (943, 1682) vs (943, 943)

In [ ]:
# Finding similarity among users

In [ ]:
# Selection of input users
Input_users = 34

In [ ]:
# Convert user sim table into dataframe
User_Sim_Table = pd.DataFrame(User_similarity)
User_Sim_Table

In [ ]:
# Finding similarity for user 34 using cosine table
Sim_Input_User = User_Sim_Table[Input_users].sort_values(ascending = True).head(5).index
Sim_Input_User

In [ ]:
# Convert the similarity values into a list
Sim_Input_User = list(Sim_Input_User)
Sim_Input_User

In [ ]:
# Select movie id from ratings table using Similarity_Input_User
Sim_User_MovieID_List = []
for Sim_User in Sim_Input_User:
    Sim = list(Ratings[Ratings['User_id']==Sim_User]['Movie_id'])
    Sim_User_MovieID_List.append(Sim)

In [ ]:
len(Sim_User_MovieID_List)

In [ ]:
print (Sim_User_MovieID_List)

In [ ]:
# Convert all the lists as a single list
import itertools
Sim_User_MovieID_Single_List = list(itertools.chain.from_iterable(Sim_User_MovieID_List))

In [ ]:
len(Sim_User_MovieID_Single_List)

In [ ]:
Unique_MovieID_Similar_User = set(Sim_User_MovieID_Single_List)

In [ ]:
len(Unique_MovieID_Similar_User)

In [ ]:
# Input movie list compare user watched 
Input_User_Watched_MovieID = list(Ratings[Ratings['User_id']==Input_users]['Movie_id'].values)
print(Input_User_Watched_MovieID)

In [ ]:
# Create a list to show movie id to users
Recom = []
for per_id in Unique_MovieID_Similar_User:
    if (per_id in Input_User_Watched_MovieID):
        pass
    else:
        Recom.append(per_id)

In [ ]:
len(Recom)

In [ ]:
print(sorted(Recom))

In [ ]:
# Cross-checking the list with Unique_MovieID_Similar_User
print(sorted(Unique_MovieID_Similar_User))

In [ ]:
# Cross-checking the list with Input_User_Watched_MovieID
print(sorted(Input_User_Watched_MovieID))

In [ ]:
# Checking common movie list
print(list(set(Unique_MovieID_Similar_User)&set(Input_User_Watched_MovieID)))

In [ ]:
User_pred = pd.DataFrame(User_prediction)
User_pred

In [ ]:
User_pred_Trans = User_pred.T
User_pred_Trans

In [ ]:
User_pred_Trans[34]

In [ ]:
gg = User_pred_Trans[34]
gg

In [ ]:
g = pd.DataFrame(gg)

In [ ]:
S = g.T
S

In [ ]:
S[187].values >= 0.4

In [ ]:
# Selection of the highest rate movies that would be selected by the user, based on user prediction
Highest_rated = []
Input_User_Pre = pd.DataFrame(User_pred_Trans[Input_users])
Input_User_Pred = Input_User_Pre.T
for Re in Recom:
    Value = Input_User_Pred[Re].values
    if(Value >= 1):
        Highest_rated.append(Re)

In [ ]:
len(Highest_rated)

In [ ]:
# Securing names
I_Cols = ['Movie id', 'Movie title', 'Release Date', 'Video Release Date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horro', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
Items = pd.read_csv('ml-100k/u.item', sep = '|', names = I_Cols, encoding = 'latin-1')

In [ ]:
# Creating movie list based on recommended movie list
Movie_title = []
for MovieID in Highest_rated:
    Movie = Items[Items['Movie id'] == MovieID]['Movie title'].values
    Movie_title.append(Movie)

In [ ]:
Movie_title

In [ ]:
# Converting into a pure list
Movie_Title_List = []
for M in Movie_title:
    print(M)
    MV = list(M)
    Movie_Title_List.append(MV)

In [ ]:
# Converting into a whole list
Final_Recommended_Movie = list(itertools.chain.from_iterable(Movie_Title_List))
Final_Recommended_Movie