# Python codes for recomendation system to determine ratings based on cotent

In [1]:
# Import Python libraries
import pandas as pd
import numpy as np

In [2]:
# Load Dataset
Col_names = ['movie id','movie title','release date','video release date','IMDb URL','Unknown','Action','Adventure','Animation','Children\'s',' Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']
Items = pd.read_csv('ml-100k/u.item', sep = '|', names = Col_names, encoding = 'latin-1')
Items.head(4)

,movie id,movie title,release date,video release date,IMDb URL,Unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# Select only the essential items
Movie_content = Items[['movie id','movie title','Action','Adventure','Animation','Children\'s',' Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']]
Movie_content

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [4]:
# Read the eratings dataset
R_cols = ['user id','item id','rating','timestamp']
Ratings = pd.read_csv('ml-100k/u.data', sep = '\t', names = R_cols, encoding = 'latin-1')
Ratings

       user id  item id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [5]:
# Checking wether it is correctly receiving the data from the user id dataset
Ratings[Ratings['user id']==196][['item id','rating']]

       item id  rating
0          242       3
940        393       4
1133       381       4
1812       251       3
1896       655       5
2374        67       5
6910       306       4
7517       238       4
7842       663       5
10017      111       4
10254      580       2
10981       25       4
13733      286       5
14606       94       3
16834      692       5
17102        8       5
17830      428       4
18853     1118       4
21605       70       3
22271       66       3
22773      257       2
23189      108       4
24030      202       3
25726      340       3
32721      287       3
33536      116       3
35197      382       4
36281      285       5
41539     1241       3
42384     1007       4
50147      411       4
52726      153       5
56628       13       2
59165      762       3
59607      173       2
60199     1022       4
60706      845       4
78787      269       3
87863      110       1

In [6]:
# Create a Pivot Table that will act as the user vector
Data_Matrix = Ratings.pivot_table(index = 'user id', columns = 'item id', values = 'rating')
Data_Matrix

item id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Replace Nan with Zero
Data_Matrix = Data_Matrix.replace(np.nan,0)
Data_Matrix

item id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# Create user vector
User_Vector = Data_Matrix.T
User_Vector

user id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
item id,,,,,,,,,,,,,,,,,,,,,
1,5.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,4.0,...,2.0,3.0,4.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0
2,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,...,5.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
5,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# Create movie vector
Movie_Vector = Items[['Action','Adventure','Animation','Children\'s',' Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']]

In [10]:
# Renaming the index
Movie_Vector.index = range(1,1683)

In [11]:
# Transposing the movie vector
Movie_Vector = Movie_Vector.T
Movie_Vector

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Action,0,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Adventure,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animation,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Children's,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Comedy,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
Crime,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documentary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Drama,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,0,1,0,1
Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Horror,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Musical,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
Sci-Fi,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Thriller,0,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
War,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Creation of content vector

In [12]:
# Combining user vector and movie vector

In [13]:
# Check the content for a random user
U1 = Ratings[Ratings['user id']==1][['item id','rating']]
U1

       item id  rating
202         61       4
305        189       3
333         33       4
334        160       4
478         20       4
...        ...     ...
92049       28       4
92487      172       5
94019      122       3
96699      152       5
99073       94       2

[272 rows x 2 columns]

In [14]:
# Create content for user based on movie id
U1_list = []
for i in U1['item id']:
    F = Movie_Vector[i].values
    U1_list.append(F)

In [15]:
# Cnverting the dataframe
U1a = pd.DataFrame(U1_list, columns = range(1,19))
U1a

     1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
1     0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   1   0   0   0   0   0   1   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
267   1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0
268   1   1   0   0   0   0   0   1   0   0   0   0   0   1   1   0   1   0
269   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
270   0   0   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[272 rows x 18 columns]

In [16]:
# Creating a single vector for an user (summing each genere column)
Single_Vector = []
for j in range(1,19):    
    g = sum(U1a[j]/272)
    Single_Vector.append(g)
Single_Vector

[0.2757352941176471,
 0.15441176470588236,
 0.044117647058823525,
 0.09191176470588235,
 0.33455882352941174,
 0.09191176470588235,
 0.01838235294117647,
 0.39338235294117646,
 0.007352941176470588,
 0.003676470588235294,
 0.04779411764705882,
 0.04779411764705882,
 0.01838235294117647,
 0.16176470588235295,
 0.15808823529411764,
 0.19117647058823528,
 0.09191176470588235,
 0.022058823529411763]

In [17]:
# Create a vector list for all users with movie vector (Created as a function)
def User_Vector(Ratings,Movie_Vector):
    Vector = []
    for user in range(1,944):
        U1 = Ratings[Ratings['user id']==user][['item id','rating']]
        U1_list = []
        for i in U1['item id']:
            F = Movie_Vector[i].values
            U1_list.append(F)
        U1a = pd.DataFrame(U1_list, columns = range(1,19))
        Single_Vector = []
        for j in range(1,19):    
            g = sum(U1a[j]/len(U1))
            Single_Vector.append(g)
        Vector.append(Single_Vector)
    return Vector

In [19]:
UV = User_Vector(Ratings,Movie_Vector)
# Converting into Data sheet
UV = pd.DataFrame(UV)
UV

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.275735,0.154412,0.044118,0.091912,0.334559,0.091912,0.018382,0.393382,0.007353,0.003676,0.047794,0.047794,0.018382,0.161765,0.158088,0.191176,0.091912,0.022059
1,0.161290,0.048387,0.016129,0.064516,0.258065,0.145161,0.000000,0.564516,0.016129,0.032258,0.032258,0.016129,0.064516,0.258065,0.064516,0.193548,0.048387,0.000000
2,0.259259,0.074074,0.000000,0.000000,0.222222,0.185185,0.018519,0.407407,0.000000,0.037037,0.092593,0.037037,0.203704,0.092593,0.148148,0.388889,0.092593,0.000000
3,0.333333,0.166667,0.000000,0.000000,0.166667,0.166667,0.041667,0.250000,0.000000,0.000000,0.041667,0.041667,0.208333,0.125000,0.250000,0.458333,0.083333,0.000000
4,0.320000,0.188571,0.080000,0.165714,0.468571,0.051429,0.000000,0.154286,0.011429,0.005714,0.160000,0.068571,0.017143,0.108571,0.188571,0.108571,0.080000,0.011429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.367347,0.204082,0.020408,0.020408,0.306122,0.061224,0.000000,0.367347,0.020408,0.000000,0.020408,0.020408,0.020408,0.204082,0.163265,0.244898,0.061224,0.000000
939,0.214953,0.112150,0.018692,0.046729,0.392523,0.065421,0.000000,0.448598,0.000000,0.028037,0.037383,0.065421,0.028037,0.224299,0.177570,0.186916,0.140187,0.000000
940,0.454545,0.318182,0.136364,0.090909,0.318182,0.045455,0.000000,0.227273,0.000000,0.000000,0.000000,0.045455,0.045455,0.045455,0.363636,0.318182,0.045455,0.000000
941,0.227848,0.139241,0.050633,0.164557,0.278481,0.000000,0.000000,0.392405,0.025316,0.012658,0.037975,0.063291,0.113924,0.215190,0.075949,0.253165,0.126582,0.037975
942,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.000000,0.339286,0.011905,0.000000,0.083333,0.023810,0.017857,0.196429,0.130952,0.208333,0.089286,0.053571

In [20]:
# Checking the shape of user vector
UV.shape

(943, 18)

In [21]:
# Checking the shape of movie vector
Movie_Vector.shape

(18, 1682)

In [23]:
# Create content vector (dot matrix) for user vector and movie vector
Content_Vector = np.dot(UV,Movie_Vector)

In [24]:
# Create data frame for the content vector
Content_Vector = pd.DataFrame(Content_Vector)

In [26]:
# Convert tthe data fram to allow access to the users
Content_Vector = Content_Vector.T
Content_Vector

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.470588,0.621324,0.191176,1.003676,0.676471,0.393382,0.551471,0.819853,0.393382,0.485294,...,0.466912,0.393382,0.393382,0.393382,0.393382,0.393382,0.352941,0.555147,0.334559,0.393382
1,0.338710,0.403226,0.193548,0.983871,0.903226,0.564516,0.629032,0.887097,0.564516,0.612903,...,0.354839,0.564516,0.564516,0.564516,0.564516,0.564516,0.451613,0.822581,0.258065,0.564516
2,0.222222,0.722222,0.388889,0.888889,0.981481,0.407407,0.555556,0.629630,0.407407,0.500000,...,0.648148,0.407407,0.407407,0.407407,0.407407,0.407407,0.481481,0.500000,0.222222,0.407407
3,0.166667,0.958333,0.458333,0.750000,0.875000,0.250000,0.500000,0.416667,0.250000,0.333333,...,0.791667,0.250000,0.250000,0.250000,0.250000,0.250000,0.583333,0.375000,0.166667,0.250000
4,0.714286,0.617143,0.108571,0.942857,0.314286,0.154286,0.342857,0.788571,0.154286,0.234286,...,0.428571,0.154286,0.154286,0.154286,0.154286,0.154286,0.217143,0.262857,0.468571,0.154286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.346939,0.816327,0.244898,1.040816,0.673469,0.367347,0.530612,0.693878,0.367347,0.428571,...,0.612245,0.367347,0.367347,0.367347,0.367347,0.367347,0.448980,0.571429,0.306122,0.367347
939,0.457944,0.514019,0.186916,1.056075,0.700935,0.448598,0.626168,0.887850,0.448598,0.588785,...,0.401869,0.448598,0.448598,0.448598,0.448598,0.448598,0.411215,0.672897,0.392523,0.448598
940,0.545455,1.090909,0.318182,1.000000,0.590909,0.227273,0.590909,0.636364,0.227273,0.272727,...,0.772727,0.227273,0.227273,0.227273,0.227273,0.227273,0.363636,0.272727,0.318182,0.227273
941,0.493671,0.620253,0.253165,0.898734,0.645570,0.392405,0.468354,0.835443,0.392405,0.518987,...,0.481013,0.392405,0.392405,0.392405,0.392405,0.392405,0.468354,0.607595,0.278481,0.392405
942,0.398810,0.797619,0.208333,1.053571,0.654762,0.339286,0.470238,0.726190,0.339286,0.428571,...,0.589286,0.339286,0.339286,0.339286,0.339286,0.339286,0.404762,0.535714,0.333333,0.339286

In [27]:
# Create a data file for back up
Content_Vector.to_csv("Content_Vector.csv", index = False)

# Individual check for the users

In [28]:
U2 = Ratings[Ratings['user id']==4]['item id'].values

In [29]:
len(U2)

24

In [30]:
Val = Content_Vector[Content_Vector[4]>(Content_Vector[4].max()-0.5)][2]
Val

1      0.193548
2      0.388889
3      0.458333
23     0.220588
26     0.520000
         ...
923    0.219512
924    0.500000
925    0.350000
928    0.265306
930    0.213115
Name: 2, Length: 314, dtype: float64

In [32]:
Recom = []
for i in Val.index:
    if i in U2:
        pass
    else:
        Recom.append(i)

In [33]:
len(Recom)

307

In [35]:
print(Recom)

[1, 2, 3, 23, 26, 28, 32, 33, 38, 39, 45, 49, 53, 68, 70, 71, 73, 75, 78, 79, 87, 98, 99, 103, 104, 105, 106, 110, 111, 112, 113, 114, 115, 119, 120, 121, 122, 125, 128, 130, 131, 132, 134, 135, 138, 139, 142, 143, 145, 146, 148, 149, 152, 154, 155, 162, 163, 164, 169, 170, 172, 174, 175, 176, 178, 184, 185, 189, 190, 200, 203, 204, 205, 211, 212, 213, 217, 219, 223, 224, 225, 226, 227, 228, 236, 239, 240, 248, 251, 256, 257, 259, 265, 272, 276, 277, 281, 283, 284, 287, 314, 315, 316, 318, 321, 322, 323, 334, 348, 350, 351, 352, 355, 371, 374, 375, 381, 382, 383, 387, 389, 390, 395, 396, 403, 407, 409, 412, 413, 414, 417, 419, 420, 422, 427, 429, 430, 432, 438, 439, 442, 443, 444, 445, 447, 448, 454, 457, 459, 461, 463, 465, 466, 467, 469, 472, 474, 484, 485, 490, 491, 493, 497, 500, 509, 510, 511, 514, 517, 518, 519, 521, 525, 526, 528, 530, 537, 543, 546, 547, 555, 556, 557, 563, 569, 572, 573, 574, 577, 582, 584, 589, 593, 597, 604, 607, 609, 610, 615, 618, 625, 626, 627, 628, 630, 632, 634, 645, 650, 654, 655, 656, 657, 661, 662, 666, 668, 672, 674, 677, 682, 684, 685, 687, 692, 694, 695, 700, 705, 709, 712, 716, 718, 719, 724, 727, 729, 732, 734, 738, 742, 743, 744, 751, 752, 753, 758, 761, 766, 771, 774, 776, 780, 783, 786, 788, 790, 791, 792, 798, 800, 807, 808, 811, 815, 816, 817, 818, 819, 826, 827, 830, 833, 835, 840, 841, 844, 852, 854, 855, 857, 862, 865, 866, 869, 872, 873, 874, 883, 890, 893, 897, 902, 904, 905, 907, 908, 909, 914, 916, 919, 922, 923, 924, 925, 928, 930]